"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import baikal.speech.recognition_config_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ForcedAlignRequest(google.protobuf.message.Message):
    """강제 정렬 요청"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAVE_FIELD_NUMBER: builtins.int
    TRANSCRIPT_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    wave: builtins.bytes
    """음성 bytes"""
    transcript: builtins.str
    """전사 내용"""
    @property
    def config(self) -> baikal.speech.recognition_config_pb2.RecognitionConfig:
        """config"""

    def __init__(
        self,
        *,
        wave: builtins.bytes = ...,
        transcript: builtins.str = ...,
        config: baikal.speech.recognition_config_pb2.RecognitionConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "transcript", b"transcript", "wave", b"wave"]) -> None: ...

global___ForcedAlignRequest = ForcedAlignRequest

@typing.final
class LongForcedAlignRequest(google.protobuf.message.Message):
    """스트리밍 강제 정렬 요청"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIG_FIELD_NUMBER: builtins.int
    TRANSCRIPT_FIELD_NUMBER: builtins.int
    WAVE_FIELD_NUMBER: builtins.int
    transcript: builtins.str
    """텍스트"""
    wave: builtins.bytes
    """음성"""
    @property
    def config(self) -> baikal.speech.recognition_config_pb2.RecognitionConfig:
        """config"""

    def __init__(
        self,
        *,
        config: baikal.speech.recognition_config_pb2.RecognitionConfig | None = ...,
        transcript: builtins.str = ...,
        wave: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "streaming_request", b"streaming_request", "transcript", b"transcript", "wave", b"wave"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "streaming_request", b"streaming_request", "transcript", b"transcript", "wave", b"wave"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["streaming_request", b"streaming_request"]) -> typing.Literal["config", "transcript", "wave"] | None: ...

global___LongForcedAlignRequest = LongForcedAlignRequest

@typing.final
class ForcedAlignResponse(google.protobuf.message.Message):
    """강제 정렬 응답"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TextSpan(google.protobuf.message.Message):
        """응답 결과"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        START_FIELD_NUMBER: builtins.int
        END_FIELD_NUMBER: builtins.int
        TEXT_FIELD_NUMBER: builtins.int
        start: builtins.float
        end: builtins.float
        text: builtins.str
        def __init__(
            self,
            *,
            start: builtins.float = ...,
            end: builtins.float = ...,
            text: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["end", b"end", "start", b"start", "text", b"text"]) -> None: ...

    TRANSCRIPT_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    WORDS_FIELD_NUMBER: builtins.int
    CHARS_FIELD_NUMBER: builtins.int
    PHONEMES_FIELD_NUMBER: builtins.int
    transcript: builtins.str
    confidence: builtins.float
    @property
    def words(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ForcedAlignResponse.TextSpan]: ...
    @property
    def chars(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ForcedAlignResponse.TextSpan]: ...
    @property
    def phonemes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ForcedAlignResponse.TextSpan]: ...
    def __init__(
        self,
        *,
        transcript: builtins.str = ...,
        confidence: builtins.float = ...,
        words: collections.abc.Iterable[global___ForcedAlignResponse.TextSpan] | None = ...,
        chars: collections.abc.Iterable[global___ForcedAlignResponse.TextSpan] | None = ...,
        phonemes: collections.abc.Iterable[global___ForcedAlignResponse.TextSpan] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["chars", b"chars", "confidence", b"confidence", "phonemes", b"phonemes", "transcript", b"transcript", "words", b"words"]) -> None: ...

global___ForcedAlignResponse = ForcedAlignResponse
