# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: baikal/speech/forced_align_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from baikal.speech import recognition_config_pb2 as baikal_dot_speech_dot_recognition__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(baikal/speech/forced_align_service.proto\x12\rbaikal.speech\x1a&baikal/speech/recognition_config.proto\"h\n\x12\x46orcedAlignRequest\x12\x0c\n\x04wave\x18\x01 \x01(\x0c\x12\x12\n\ntranscript\x18\x02 \x01(\t\x12\x30\n\x06\x63onfig\x18\x03 \x01(\x0b\x32 .baikal.speech.RecognitionConfig\"\x87\x01\n\x16LongForcedAlignRequest\x12\x32\n\x06\x63onfig\x18\x01 \x01(\x0b\x32 .baikal.speech.RecognitionConfigH\x00\x12\x14\n\ntranscript\x18\x02 \x01(\tH\x00\x12\x0e\n\x04wave\x18\x03 \x01(\x0cH\x00\x42\x13\n\x11streaming_request\"\xaa\x02\n\x13\x46orcedAlignResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12:\n\x05words\x18\x03 \x03(\x0b\x32+.baikal.speech.ForcedAlignResponse.TextSpan\x12:\n\x05\x63hars\x18\x04 \x03(\x0b\x32+.baikal.speech.ForcedAlignResponse.TextSpan\x12=\n\x08phonemes\x18\x05 \x03(\x0b\x32+.baikal.speech.ForcedAlignResponse.TextSpan\x1a\x34\n\x08TextSpan\x12\r\n\x05start\x18\x01 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x02\x12\x0c\n\x04text\x18\x03 \x01(\t2\xce\x01\n\x12\x46orcedAlignService\x12V\n\x0b\x46orcedAlign\x12!.baikal.speech.ForcedAlignRequest\x1a\".baikal.speech.ForcedAlignResponse\"\x00\x12`\n\x0fLongForcedAlign\x12%.baikal.speech.LongForcedAlignRequest\x1a\".baikal.speech.ForcedAlignResponse\"\x00(\x01\x42:B\x17\x46orcedAlignServiceProtoP\x01Z\x1d\x62\x61ikal.ai/proto/baikal/speechb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'baikal.speech.forced_align_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\027ForcedAlignServiceProtoP\001Z\035baikal.ai/proto/baikal/speech'
  _globals['_FORCEDALIGNREQUEST']._serialized_start=99
  _globals['_FORCEDALIGNREQUEST']._serialized_end=203
  _globals['_LONGFORCEDALIGNREQUEST']._serialized_start=206
  _globals['_LONGFORCEDALIGNREQUEST']._serialized_end=341
  _globals['_FORCEDALIGNRESPONSE']._serialized_start=344
  _globals['_FORCEDALIGNRESPONSE']._serialized_end=642
  _globals['_FORCEDALIGNRESPONSE_TEXTSPAN']._serialized_start=590
  _globals['_FORCEDALIGNRESPONSE_TEXTSPAN']._serialized_end=642
  _globals['_FORCEDALIGNSERVICE']._serialized_start=645
  _globals['_FORCEDALIGNSERVICE']._serialized_end=851
# @@protoc_insertion_point(module_scope)
