"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _AudioEncoding:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AudioEncodingEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AudioEncoding.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN_ENCODING: _AudioEncoding.ValueType  # 0
    LINEAR16: _AudioEncoding.ValueType  # 1
    """FLAC = 2;
    MULAW = 3;
    AMR = 4;
    AMR_WB = 5;
    OGG_OPUS = 6;
    SPEEX_WITH_HEADER_BYTE = 7;
    WEBM_OPUS = 8;
    """

class AudioEncoding(_AudioEncoding, metaclass=_AudioEncodingEnumTypeWrapper): ...

UNKNOWN_ENCODING: AudioEncoding.ValueType  # 0
LINEAR16: AudioEncoding.ValueType  # 1
"""FLAC = 2;
MULAW = 3;
AMR = 4;
AMR_WB = 5;
OGG_OPUS = 6;
SPEEX_WITH_HEADER_BYTE = 7;
WEBM_OPUS = 8;
"""
global___AudioEncoding = AudioEncoding

@typing.final
class RecognitionConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENCODING_FIELD_NUMBER: builtins.int
    SAMPLE_RATE_FIELD_NUMBER: builtins.int
    CHANNEL_COUNT_FIELD_NUMBER: builtins.int
    ENABLE_CONFIDENCE_FIELD_NUMBER: builtins.int
    ENABLE_WORD_TIME_OFFSETS_FIELD_NUMBER: builtins.int
    ENABLE_CHAR_TIME_OFFSETS_FIELD_NUMBER: builtins.int
    ENABLE_PHONEME_TIME_OFFSETS_FIELD_NUMBER: builtins.int
    encoding: global___AudioEncoding.ValueType
    """오디오 포맷(현재는 LINEAR16만 지원)"""
    sample_rate: builtins.int
    """샘플레이트(Hertz)"""
    channel_count: builtins.int
    """채널 수"""
    enable_confidence: builtins.bool
    """confidence 표시"""
    enable_word_time_offsets: builtins.bool
    """어절 오프셋 표시"""
    enable_char_time_offsets: builtins.bool
    """음절 오프셋 표시"""
    enable_phoneme_time_offsets: builtins.bool
    """음소 오프셋 표시
    채널 분리해서 각각 음성 인식
    bool enable_separate_recognition_per_channel = 8;
    언어 코드
    string language_code = 9;
    대체 언어 코드
    repeated string alternative_language_codes = 10;
    대체 단어 개수
    int32 max_alternatives = 11;
    """
    def __init__(
        self,
        *,
        encoding: global___AudioEncoding.ValueType = ...,
        sample_rate: builtins.int = ...,
        channel_count: builtins.int = ...,
        enable_confidence: builtins.bool = ...,
        enable_word_time_offsets: builtins.bool = ...,
        enable_char_time_offsets: builtins.bool = ...,
        enable_phoneme_time_offsets: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channel_count", b"channel_count", "enable_char_time_offsets", b"enable_char_time_offsets", "enable_confidence", b"enable_confidence", "enable_phoneme_time_offsets", b"enable_phoneme_time_offsets", "enable_word_time_offsets", b"enable_word_time_offsets", "encoding", b"encoding", "sample_rate", b"sample_rate"]) -> None: ...

global___RecognitionConfig = RecognitionConfig

@typing.final
class StreamRecognitionConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENCODING_FIELD_NUMBER: builtins.int
    SAMPLE_RATE_FIELD_NUMBER: builtins.int
    CHANNEL_COUNT_FIELD_NUMBER: builtins.int
    ENABLE_CONFIDENCE_FIELD_NUMBER: builtins.int
    ENABLE_WORD_TIME_OFFSETS_FIELD_NUMBER: builtins.int
    ENABLE_CHAR_TIME_OFFSETS_FIELD_NUMBER: builtins.int
    ENABLE_PHONEME_TIME_OFFSETS_FIELD_NUMBER: builtins.int
    encoding: global___AudioEncoding.ValueType
    """오디오 포맷(현재는 LINEAR16만 지원)"""
    sample_rate: builtins.int
    """샘플레이트(Hertz)"""
    channel_count: builtins.int
    """채널 수"""
    enable_confidence: builtins.bool
    """confidence 표시"""
    enable_word_time_offsets: builtins.bool
    """어절 오프셋 표시"""
    enable_char_time_offsets: builtins.bool
    """음절 오프셋 표시"""
    enable_phoneme_time_offsets: builtins.bool
    """음소 오프셋 표시
    // 첫 문장 인식 후 종료
    bool single_utterance = 9;
    채널 분리해서 각각 음성 인식
    bool enable_separate_recognition_per_channel = 9;
    언어 코드
    string language_code = 10;
    대체 언어 코드
    repeated string alternative_language_codes = 11;
    대체 단어 개수
    int32 max_alternatives = 12;
    """
    def __init__(
        self,
        *,
        encoding: global___AudioEncoding.ValueType = ...,
        sample_rate: builtins.int = ...,
        channel_count: builtins.int = ...,
        enable_confidence: builtins.bool = ...,
        enable_word_time_offsets: builtins.bool = ...,
        enable_char_time_offsets: builtins.bool = ...,
        enable_phoneme_time_offsets: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channel_count", b"channel_count", "enable_char_time_offsets", b"enable_char_time_offsets", "enable_confidence", b"enable_confidence", "enable_phoneme_time_offsets", b"enable_phoneme_time_offsets", "enable_word_time_offsets", b"enable_word_time_offsets", "encoding", b"encoding", "sample_rate", b"sample_rate"]) -> None: ...

global___StreamRecognitionConfig = StreamRecognitionConfig
