"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class STTRequest(google.protobuf.message.Message):
    """음성 인식 요청"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAVE_FIELD_NUMBER: builtins.int
    wave: builtins.bytes
    """음성 파일 원본"""
    def __init__(
        self,
        *,
        wave: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["wave", b"wave"]) -> None: ...

global___STTRequest = STTRequest

@typing.final
class STTResponse(google.protobuf.message.Message):
    """음성 인식 응답"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TextSpan(google.protobuf.message.Message):
        """응답 결과"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        START_FIELD_NUMBER: builtins.int
        END_FIELD_NUMBER: builtins.int
        TEXT_FIELD_NUMBER: builtins.int
        start: builtins.float
        end: builtins.float
        text: builtins.str
        def __init__(
            self,
            *,
            start: builtins.float = ...,
            end: builtins.float = ...,
            text: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["end", b"end", "start", b"start", "text", b"text"]) -> None: ...

    TRANSCRIPT_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    WORDS_FIELD_NUMBER: builtins.int
    CHARS_FIELD_NUMBER: builtins.int
    PHONEMES_FIELD_NUMBER: builtins.int
    transcript: builtins.str
    confidence: builtins.float
    @property
    def words(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___STTResponse.TextSpan]: ...
    @property
    def chars(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___STTResponse.TextSpan]: ...
    @property
    def phonemes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___STTResponse.TextSpan]: ...
    def __init__(
        self,
        *,
        transcript: builtins.str = ...,
        confidence: builtins.float = ...,
        words: collections.abc.Iterable[global___STTResponse.TextSpan] | None = ...,
        chars: collections.abc.Iterable[global___STTResponse.TextSpan] | None = ...,
        phonemes: collections.abc.Iterable[global___STTResponse.TextSpan] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["chars", b"chars", "confidence", b"confidence", "phonemes", b"phonemes", "transcript", b"transcript", "words", b"words"]) -> None: ...

global___STTResponse = STTResponse
