"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import baikal.speech.recognition_config_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RecognizeRequest(google.protobuf.message.Message):
    """음성 인식 요청"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAVE_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    wave: builtins.bytes
    """음성 bytes"""
    @property
    def config(self) -> baikal.speech.recognition_config_pb2.RecognitionConfig:
        """config"""

    def __init__(
        self,
        *,
        wave: builtins.bytes = ...,
        config: baikal.speech.recognition_config_pb2.RecognitionConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "wave", b"wave"]) -> None: ...

global___RecognizeRequest = RecognizeRequest

@typing.final
class StreamRecognizeRequest(google.protobuf.message.Message):
    """스트리밍 음성 인식 요청"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIG_FIELD_NUMBER: builtins.int
    WAVE_FIELD_NUMBER: builtins.int
    wave: builtins.bytes
    @property
    def config(self) -> baikal.speech.recognition_config_pb2.StreamRecognitionConfig: ...
    def __init__(
        self,
        *,
        config: baikal.speech.recognition_config_pb2.StreamRecognitionConfig | None = ...,
        wave: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "streaming_request", b"streaming_request", "wave", b"wave"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "streaming_request", b"streaming_request", "wave", b"wave"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["streaming_request", b"streaming_request"]) -> typing.Literal["config", "wave"] | None: ...

global___StreamRecognizeRequest = StreamRecognizeRequest

@typing.final
class RecognizeResponse(google.protobuf.message.Message):
    """음성 인식 응답"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TextSpan(google.protobuf.message.Message):
        """응답 결과"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        START_FIELD_NUMBER: builtins.int
        END_FIELD_NUMBER: builtins.int
        TEXT_FIELD_NUMBER: builtins.int
        start: builtins.float
        end: builtins.float
        text: builtins.str
        def __init__(
            self,
            *,
            start: builtins.float = ...,
            end: builtins.float = ...,
            text: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["end", b"end", "start", b"start", "text", b"text"]) -> None: ...

    TRANSCRIPT_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    WORDS_FIELD_NUMBER: builtins.int
    CHARS_FIELD_NUMBER: builtins.int
    PHONEMES_FIELD_NUMBER: builtins.int
    transcript: builtins.str
    confidence: builtins.float
    @property
    def words(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RecognizeResponse.TextSpan]: ...
    @property
    def chars(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RecognizeResponse.TextSpan]: ...
    @property
    def phonemes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RecognizeResponse.TextSpan]: ...
    def __init__(
        self,
        *,
        transcript: builtins.str = ...,
        confidence: builtins.float = ...,
        words: collections.abc.Iterable[global___RecognizeResponse.TextSpan] | None = ...,
        chars: collections.abc.Iterable[global___RecognizeResponse.TextSpan] | None = ...,
        phonemes: collections.abc.Iterable[global___RecognizeResponse.TextSpan] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["chars", b"chars", "confidence", b"confidence", "phonemes", b"phonemes", "transcript", b"transcript", "words", b"words"]) -> None: ...

global___RecognizeResponse = RecognizeResponse
