# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from baikal.speech import stt_service_pb2 as baikal_dot_speech_dot_stt__service__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in baikal/speech/stt_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RecognizeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recognize = channel.unary_unary(
                '/baikal.speech.RecognizeService/Recognize',
                request_serializer=baikal_dot_speech_dot_stt__service__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=baikal_dot_speech_dot_stt__service__pb2.RecognizeResponse.FromString,
                _registered_method=True)
        self.LongRecognize = channel.stream_unary(
                '/baikal.speech.RecognizeService/LongRecognize',
                request_serializer=baikal_dot_speech_dot_stt__service__pb2.StreamRecognizeRequest.SerializeToString,
                response_deserializer=baikal_dot_speech_dot_stt__service__pb2.RecognizeResponse.FromString,
                _registered_method=True)
        self.StreamRecognize = channel.stream_stream(
                '/baikal.speech.RecognizeService/StreamRecognize',
                request_serializer=baikal_dot_speech_dot_stt__service__pb2.StreamRecognizeRequest.SerializeToString,
                response_deserializer=baikal_dot_speech_dot_stt__service__pb2.RecognizeResponse.FromString,
                _registered_method=True)


class RecognizeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Recognize(self, request, context):
        """음성 인식
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LongRecognize(self, request_iterator, context):
        """긴 음성 인식
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRecognize(self, request_iterator, context):
        """스트리밍 음성 인식
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecognizeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=baikal_dot_speech_dot_stt__service__pb2.RecognizeRequest.FromString,
                    response_serializer=baikal_dot_speech_dot_stt__service__pb2.RecognizeResponse.SerializeToString,
            ),
            'LongRecognize': grpc.stream_unary_rpc_method_handler(
                    servicer.LongRecognize,
                    request_deserializer=baikal_dot_speech_dot_stt__service__pb2.StreamRecognizeRequest.FromString,
                    response_serializer=baikal_dot_speech_dot_stt__service__pb2.RecognizeResponse.SerializeToString,
            ),
            'StreamRecognize': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamRecognize,
                    request_deserializer=baikal_dot_speech_dot_stt__service__pb2.StreamRecognizeRequest.FromString,
                    response_serializer=baikal_dot_speech_dot_stt__service__pb2.RecognizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'baikal.speech.RecognizeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('baikal.speech.RecognizeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecognizeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baikal.speech.RecognizeService/Recognize',
            baikal_dot_speech_dot_stt__service__pb2.RecognizeRequest.SerializeToString,
            baikal_dot_speech_dot_stt__service__pb2.RecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LongRecognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/baikal.speech.RecognizeService/LongRecognize',
            baikal_dot_speech_dot_stt__service__pb2.StreamRecognizeRequest.SerializeToString,
            baikal_dot_speech_dot_stt__service__pb2.RecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRecognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/baikal.speech.RecognizeService/StreamRecognize',
            baikal_dot_speech_dot_stt__service__pb2.StreamRecognizeRequest.SerializeToString,
            baikal_dot_speech_dot_stt__service__pb2.RecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
