# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: baikal/speech/stt_service_v1.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"baikal/speech/stt_service_v1.proto\x12\rbaikal.speech\"\x1a\n\nSTTRequest\x12\x0c\n\x04wave\x18\x01 \x01(\x0c\"\x8a\x02\n\x0bSTTResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\x32\n\x05words\x18\x03 \x03(\x0b\x32#.baikal.speech.STTResponse.TextSpan\x12\x32\n\x05\x63hars\x18\x04 \x03(\x0b\x32#.baikal.speech.STTResponse.TextSpan\x12\x35\n\x08phonemes\x18\x05 \x03(\x0b\x32#.baikal.speech.STTResponse.TextSpan\x1a\x34\n\x08TextSpan\x12\r\n\x05start\x18\x01 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x02\x12\x0c\n\x04text\x18\x03 \x01(\t2L\n\nSTTService\x12>\n\x03STT\x12\x19.baikal.speech.STTRequest\x1a\x1a.baikal.speech.STTResponse\"\x00\x42\x32\x42\x0fSTTServiceProtoP\x01Z\x1d\x62\x61ikal.ai/proto/baikal/speechb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'baikal.speech.stt_service_v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\017STTServiceProtoP\001Z\035baikal.ai/proto/baikal/speech'
  _globals['_STTREQUEST']._serialized_start=53
  _globals['_STTREQUEST']._serialized_end=79
  _globals['_STTRESPONSE']._serialized_start=82
  _globals['_STTRESPONSE']._serialized_end=348
  _globals['_STTRESPONSE_TEXTSPAN']._serialized_start=296
  _globals['_STTRESPONSE_TEXTSPAN']._serialized_end=348
  _globals['_STTSERVICE']._serialized_start=350
  _globals['_STTSERVICE']._serialized_end=426
# @@protoc_insertion_point(module_scope)
