"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import baikal.speech.vad_service_pb2
import collections.abc
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class VADServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    GetVADSpan: grpc.UnaryUnaryMultiCallable[
        baikal.speech.vad_service_pb2.VADRequest,
        baikal.speech.vad_service_pb2.GetVADSpanResponse,
    ]

class VADServiceAsyncStub:
    GetVADSpan: grpc.aio.UnaryUnaryMultiCallable[
        baikal.speech.vad_service_pb2.VADRequest,
        baikal.speech.vad_service_pb2.GetVADSpanResponse,
    ]

class VADServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def GetVADSpan(
        self,
        request: baikal.speech.vad_service_pb2.VADRequest,
        context: _ServicerContext,
    ) -> typing.Union[baikal.speech.vad_service_pb2.GetVADSpanResponse, collections.abc.Awaitable[baikal.speech.vad_service_pb2.GetVADSpanResponse]]: ...

def add_VADServiceServicer_to_server(servicer: VADServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
