"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class VADRequest(google.protobuf.message.Message):
    """음성 인식 요청"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAVE_FIELD_NUMBER: builtins.int
    wave: builtins.bytes
    """음성 파일 원본"""
    def __init__(
        self,
        *,
        wave: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["wave", b"wave"]) -> None: ...

global___VADRequest = VADRequest

@typing.final
class GetVADSpanResponse(google.protobuf.message.Message):
    """음성 활동 시간"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VOICE_SPANS_FIELD_NUMBER: builtins.int
    @property
    def voice_spans(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___VoiseSpan]: ...
    def __init__(
        self,
        *,
        voice_spans: collections.abc.Iterable[global___VoiseSpan] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["voice_spans", b"voice_spans"]) -> None: ...

global___GetVADSpanResponse = GetVADSpanResponse

@typing.final
class VoiseSpan(google.protobuf.message.Message):
    """Voice Span"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    start: builtins.float
    end: builtins.float
    def __init__(
        self,
        *,
        start: builtins.float = ...,
        end: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["end", b"end", "start", b"start"]) -> None: ...

global___VoiseSpan = VoiseSpan
